### ISSUE TITLE
3D材质包并不能转换

### ISSUE THREAD

**Issue by luomoxiao** [icrdr/Resource-Pack-Converter#3]
我的一个3D材质包，只是有3D模型的一个默认材质包，不能经过你的程序转化，不会出来结果

**Comment by icrdr** [comment]
请你把材质包发我，我看看什么原因

**Comment by luomoxiao** [comment]
[default_3d_models_v3.5.zip](https://github.com/icrdr/Resource-Pack-Converter/files/2312750/default_3d_models_v3.5.zip)
是这一个材质

**Comment by icrdr** [comment]
好的，感谢！我抽空看一下

luomoxiao <notifications@github.com> 于2018年8月23日周四 上午11:11写道：
